.TH PLOT 1 "January 15, 2023"
.AT 3
.SH NAME
plot, tplot, vplot, plottoa, atoplot \- plotting utilities
.SH SYNOPSIS
.B plot
.BR \-Tdriver
[...]
.SH DESCRIPTION
These commands read plotting instructions (see
.IR  plot (5))
from the standard input or the specified
.IR files ,
and in general
produce plotting instructions suitable for
a particular
.I driver
on the standard output.
The
.B \-r
flag may be used to specify the device's output resolution
(currently only the Imagen laser printer understands this option).
Command
.I tplot
is an alias to
.I plot
for compatibility with SVR4.
Commands
.I atoplot
and
.I plottoa
are for converting between ASCII and binary representations of plotting instructions.
.PP
Known
.I drivers
are:
.TP
.B 4013
Tektronix 4013 storage scope.
.TP
.BR 4014\  or\  tek
Tektronix 4014 or 4015 storage scope with Enhanced Graphics Module.
Use 4013 for Tektronix 4014 or 4015 without the Enhanced Graphics Module.
.TP
.B 450
DASI Hyterm 450 terminal (Diablo mechanism).
.TP
.B 300
DASI 300 or GSI terminal (Diablo mechanism).
.TP
.B 300S
DASI 300S terminal (Diablo mechanism).
.TP
.B aed
AED 512 color graphics terminal.
.TP
.BR bitgraph\  or\  bg
BBN bitgraph graphics terminal.
.TP
.BR imagen\  or\  ip
Imagen laser printer (default 240 dots-per-inch resolution).
.TP
.B crt
Any crt terminal capable of running
.IR vi (1).
.TP
.B dumb
Dumb terminals without cursor addressing or line printers.
.TP
.B vt125
DEC vt125 terminal.
.TP
.BR hp2648\  or\  hp\  or\  hp8
Hewlett Packard 2648 graphics terminal.
.TP
.B ver
Versatec D1200A printer-plotter.
This driver is an alias to the
.I vplot
command and sends result directly to the plotter device
.I /dev/vp0
rather than to the standard output. Also it places a scan-converted image in the
.I /var/tmp/raster
file.
.SH FILES
/opt/bsd-plotutils/bin/plot
.br
/opt/bsd-plotutils/bin/tplot
.br
/opt/bsd-plotutils/bin/atoplot
.br
/opt/bsd-plotutils/bin/plottoa
.br
/opt/bsd-plotutils/bin/vplot
.br
/var/tmp/raster
.br
/opt/bsd-plotutils/plot/t4013
.br
/opt/bsd-plotutils/plot/tek
.br
/opt/bsd-plotutils/plot/t450
.br
/opt/bsd-plotutils/plot/t300
.br
/opt/bsd-plotutils/plot/t300s
.br
/opt/bsd-plotutils/plot/aedplot
.br
/opt/bsd-plotutils/plot/bgplot
.br
/opt/bsd-plotutils/plot/dumbplot
.br
/opt/bsd-plotutils/plot/gigiplot
.br
/opt/bsd-plotutils/plot/hpplot
.br
/opt/bsd-plotutils/plot/implot
.SH "SEE ALSO"
plot(3), plot(5)
