.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"     @(#)graph.1	6.3 (Berkeley) 7/24/90
.\"
.Dd August 7, 2018
.Dt GRAPH 1
.Os
.Sh NAME
.Nm graph
.Nd draw a graph
.Sh SYNOPSIS
.Nm graph
.Op option
\&...
.Sh DESCRIPTION
.Nm graph
with no options takes pairs of numbers from the
standard input as abscissas and
ordinates of a graph.
Successive points are connected by straight lines.
The graph is encoded on the standard output
for display by the
.Xr plot 1
filters.
.Pp
If the coordinates of a point are followed by
a nonnumeric string, that string is printed as a
label beginning on the point.
Labels may be surrounded with quotes "...", in
which case they may be empty or contain blanks
and numbers;
labels never contain newlines.
.Pp
The following options are recognized,
each as a separate argument.
.Bl -tag -width Ds
.It Fl a
Supply abscissas automatically (they are missing from
the input); spacing is given by the next
argument (default 1).
A second optional argument is the starting point for
automatic abscissas (default 0 or lower limit given by
.Fl x  ) .
.It Fl b
Break (disconnect) the graph after each label in the input.
.It Fl c
Character string given by next argument
is default label for each point.
.It Fl g
Next argument is grid style,
0 no grid, 1 frame with ticks, 2 full grid (default).
.It Fl l
Next argument is label for graph.
.It Fl m
Next argument is mode (style)
of connecting lines:
0 disconnected, 1 connected (default).
Some devices give distinguishable line styles
for other small integers.
.It Fl d
Disconnected line style (alias for -m 0)
.It Fl s
Save screen, don't erase before plotting. (it may not have an effect on some devices)
.It Fl y
Similarly for
.Ar y  .
.It Fl h
Next argument is fraction of space for height.
.It Fl w
Similarly for width.
.It Fl r
Next argument is fraction of space to move right before plotting.
.It Fl u
Similarly to move up before plotting.
.It Fl t
Transpose horizontal and vertical axes.
(Option
.It Fl x
Transpose vertical axis.
.El
.Tp
.Pp
If a specified lower limit exceeds the upper limit,
the axis
is reversed.
.Sh SEE ALSO
.Xr spline 1 ,
.Xr plot 1
.Sh HISTORY
.Nm plot
appeared in Version 6 AT&T Unix.
.Sh BUGS
.Nm graph
stores all points internally and drops those for which
there isn't room.
.Pp
Segments that run out of bounds are dropped, not windowed.
.Pp
Logarithmic axes may not be reversed.
