#	@(#)Makefile	4.4 (Berkeley) 5/11/90

LIB=	plot
LIBDIR=	/usr/local/lib
SRCS=	arc.c box.c circle.c close.c cont.c dot.c erase.c label.c \
	line.c linmod.c move.c open.c point.c putsi.c space.c
MAN=	plot.3
MANDIR=	/usr/local/man/man

.include <bsd.lib.mk>
