.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"     @(#)plot.1	6.6 (Berkeley) 7/24/90
.\"
.Dd August 5, 2018
.Dt PLOT 1
.Os
.Sh NAME
.Nm plot, bgplot, crtplot, dumbplot, gigiplot, grnplot, hp7221plot, implot, t4013plot, tekplot, plottoa, atoplot
.Nd graphics filters for various plotters
.Sh SYNOPSIS
.Nm plot
.Oo
.Op Fl T Ar terminal
.Oo
.Ar
.Sh DESCRIPTION
These commands read plotting instructions (see
.Xr plot  5  )
from the standard input or the specified
.Ar files  ,
and in general
produce plotting instructions suitable for
a particular
.Ar terminal
on the standard output.
The
.Fl r
flag may be used to specify the device's output resolution
(currently only the Imagen laser printer understands this option).
.Pp
If no
.Ar terminal
type is specified, the environment parameter
.Ev $TERM
(see
.Xr environ  7  )
is used.
Known
.Ar terminals
are:
.Bl -tag -width Ds
.It Pa 4013
Tektronix 4013 storage scope.
.It Pa 4014
Tektronix 4014 or 4015 storage scope with Enhanced Graphics Module.
(Use 4013 for Tektronix 4014 or 4015 without the Enhanced Graphics Module).
.It Pa bitgraph
BBN bitgraph graphics terminal.
.It Pa imagen
Imagen laser printer (default 240 dots-per-inch resolution).
.It Pa crt
Any crt terminal capable of running vi.
.It Pa dumb
Dumb terminals without cursor addressing or line printers.
.It Pa X
Any graphics workstation with XTerm that have support for Tektronix emulation.
.It Pa vt0
DEC vt100 terminal.
.It Pa hp2648
Hewlett Packard 2648 graphics terminal.
.El
.Sh ENVIRONMENT
.Bl -tag -width
.It Ev TERM
Used to determine the terminal type if not given as an argument.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /usr/local/bin/t4013plot
.It Pa /usr/local/bin/tekplot
.It Pa /usr/local/bin/bgplot
.It Pa /usr/local/bin/crtplot
.It Pa /usr/local/bin/dumbplot
.It Pa /usr/local/bin/gigiplot
.It Pa /usr/local/bin/implot
.It Pa /usr/local/bin/plot
.El
.Sh SEE ALSO
.Xr plot 3 ,
.Xr plot 5 ,
.Xr f77plot 3
.Sh HISTORY
.Nm plot
appeared in Version 6 AT&T UNIX.
