LIB=	plot_ascii
SRCS=	arc.c box.c circle.c close.c cont.c dot.c erase.c label.c \
	line.c linemod.c move.c open.c point.c space.c subr.c
LDADD+=	-lm -ltermcap
SHLIB_MAJOR=	1
SHLIB_MINOR=	0

.include <bsd.lib.mk>