#	@(#)Makefile	5.3 (Berkeley) 5/12/90

LIB=	plotdumb
LIBDIR=	/usr/local/lib
SRCS=	arc.c box.c circle.c close.c cont.c dot.c erase.c label.c \
	line.c linemod.c move.c open.c point.c space.c subr.c

.include <bsd.lib.mk>
