#	@(#)Makefile	4.15 (Berkeley) 5/11/90

SUBDIR=	bitgraph dumb gigi grn hp7221 imagen plot \
	t4013 t4014 vt0 f77plot

# hp2648, t300, t300s, t450, and aed are depend on sgtty.h which is no longer exist in many modern OSes.

.include <bsd.subdir.mk>
